// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb30-nCHAXdh6TG8JKTvzEgmaMx1jmrf8',
    appId: '1:414800948516:web:01e5066a60379c06ba97b1',
    messagingSenderId: '414800948516',
    projectId: 'kanban-app-d269e',
    authDomain: 'kanban-app-d269e.firebaseapp.com',
    storageBucket: 'kanban-app-d269e.firebasestorage.app',
    measurementId: 'G-ZZP86TPW5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8RNDeafADJYY6Iug2nnBAPyuI-t-Llw',
    appId: '1:414800948516:android:604b566af5843750ba97b1',
    messagingSenderId: '414800948516',
    projectId: 'kanban-app-d269e',
    storageBucket: 'kanban-app-d269e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwhMJkzijv3kBWOtbRB7wVu-_MMH4M7s0',
    appId: '1:414800948516:ios:bffb5d4b58bd7c89ba97b1',
    messagingSenderId: '414800948516',
    projectId: 'kanban-app-d269e',
    storageBucket: 'kanban-app-d269e.firebasestorage.app',
    iosBundleId: 'com.example.kanbanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwhMJkzijv3kBWOtbRB7wVu-_MMH4M7s0',
    appId: '1:414800948516:ios:bffb5d4b58bd7c89ba97b1',
    messagingSenderId: '414800948516',
    projectId: 'kanban-app-d269e',
    storageBucket: 'kanban-app-d269e.firebasestorage.app',
    iosBundleId: 'com.example.kanbanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb30-nCHAXdh6TG8JKTvzEgmaMx1jmrf8',
    appId: '1:414800948516:web:5da26946657a1fb2ba97b1',
    messagingSenderId: '414800948516',
    projectId: 'kanban-app-d269e',
    authDomain: 'kanban-app-d269e.firebaseapp.com',
    storageBucket: 'kanban-app-d269e.firebasestorage.app',
    measurementId: 'G-Y8H0MTQ4TR',
  );
}
